# Generated by Django 5.1.3 on 2025-03-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formkit_ninja",
            "0026_remove_formkitschemanode_protect_node_deletes_and_updates_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("published_schema", models.JSONField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formkit_ninja.formkitschema",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schema", "is_active"), name="unique_active_schema"
                    )
                ],
            },
        ),
    ]
