# Generated by Django 5.1.3 on 2025-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0027_publishedform"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="publishedform",
            name="unique_active_schema",
        ),
        migrations.AlterField(
            model_name="publishedform",
            name="published_schema",
            field=models.JSONField(editable=False),
        ),
    ]
