# Generated by Django 5.1.3 on 2025-04-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0028_remove_publishedform_unique_active_schema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedform",
            name="replaced",
            field=models.DateTimeField(
                blank=True,
                help_text="When this form version was replaced by a newer version",
                null=True,
            ),
        ),
    ]
