# Generated by Django 5.1.3 on 2025-04-11 10:46

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formkit_ninja', '0031_remove_formkitschemanode_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='formkitschemanode',
            trigger=pgtrigger.compiler.Trigger(name='assign_order_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."order" IS NULL)', func='\n            NEW.order = (\n                SELECT COALESCE(MAX("order"), 0) + 1\n                FROM formkit_ninja_formkitschemanode\n                WHERE schema_id = NEW.schema_id\n            );\n            RETURN NEW;\n        ', hash='6229f11cb59b4075b222ac375e0bd8843cae6c0b', operation='INSERT', pgid='pgtrigger_assign_order_on_insert_94ef5', table='formkit_ninja_formkitschemanode', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='formkitschemanode',
            trigger=pgtrigger.compiler.Trigger(name='increment_higher_orders', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."order" IS NOT NULL)', func='\n            UPDATE formkit_ninja_formkitschemanode\n            SET "order" = "order" + 1\n            WHERE schema_id = NEW.schema_id\n            AND "order" >= NEW."order"\n            AND id != NEW.id\n            AND pg_trigger_depth() = 1;\n            RETURN NEW;\n        ', hash='f50d774de8b02bc398bc40b15263b89f3774c30e', operation='INSERT OR UPDATE', pgid='pgtrigger_increment_higher_orders_38803', table='formkit_ninja_formkitschemanode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='formkitschemanode',
            trigger=pgtrigger.compiler.Trigger(name='decrement_higher_orders', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."order" IS NOT NULL AND (NOT NEW."is_active" OR NEW."order" IS NULL))', func='\n            UPDATE formkit_ninja_formkitschemanode\n            SET "order" = "order" - 1\n            WHERE schema_id = OLD.schema_id\n            AND "order" > OLD."order";\n            RETURN OLD;\n        ', hash='f78f8507727a65db410e5e5045c10be4f5e4698b', operation='UPDATE', pgid='pgtrigger_decrement_higher_orders_921a5', table='formkit_ninja_formkitschemanode', when='BEFORE')),
        ),
    ]
