# Generated by Django 5.1.3 on 2025-04-13 05:44

from django.db import migrations, models


def set_initial_status(apps, schema_editor):
    """Set the initial status for existing PublishedForms"""
    PublishedForm = apps.get_model('formkit_ninja', 'PublishedForm')
    
    # Update all forms that have been replaced (not active and have a replaced date)
    PublishedForm.objects.filter(
        is_active=False,
        replaced__isnull=False
    ).update(status='replaced')
    
    # Update all active forms as published
    PublishedForm.objects.filter(
        is_active=True
    ).update(status='published')
    
    # Any remaining forms are drafts (which is the default, so we don't need to set them)


def reverse_status(apps, schema_editor):
    """Reverse the status changes (though the default will handle this automatically)"""
    PublishedForm = apps.get_model('formkit_ninja', 'PublishedForm')
    PublishedForm.objects.all().update(status='draft')


class Migration(migrations.Migration):

    dependencies = [
        ('formkit_ninja', '0032_formkitschemanode_assign_order_on_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('replaced', 'Replaced')], default='draft', help_text='Current status of the form', max_length=20),
        ),
        migrations.RunPython(set_initial_status, reverse_status),
    ]
