# Generated by Django 5.1.3 on 2025-04-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formkit_ninja', '0033_publishedform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedform',
            name='is_active',
        ),
    ]
