# Generated by Django 5.1.3 on 2025-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formkit_ninja', '0034_remove_publishedform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedform',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
