# Generated by Django 5.2.1 on 2026-01-19 08:26

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0035_publishedform_version"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="decrement_higher_orders",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="formkitschemanode",
            trigger=pgtrigger.compiler.Trigger(
                name="decrement_higher_orders",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."order" IS NOT NULL AND (NOT NEW."is_active" OR NEW."order" IS NULL))',
                    func='\n            UPDATE formkit_ninja_formkitschemanode\n            SET "order" = "order" - 1\n            WHERE schema_id = OLD.schema_id\n            AND "order" > OLD."order";\n            RETURN NEW;\n        ',
                    hash="37d7782b567ed790f0fe3128ac14c3ae9ded539b",
                    operation="UPDATE",
                    pgid="pgtrigger_decrement_higher_orders_921a5",
                    table="formkit_ninja_formkitschemanode",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="publishedform",
            constraint=models.UniqueConstraint(fields=("schema", "version"), name="unique_schema_version"),
        ),
    ]
