# Generated by Django 4.2.27 on 2026-02-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formkit_ninja', '0037_alter_formkitschemanode_django_field_args_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='formkit_ninja.separatedsubmission')),
                ('full_name', models.TextField(blank='True', null='True')),
                ('email_address', models.TextField(blank='True', null='True')),
            ],
        ),
    ]
