[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "formkit_ninja"
version = "0.1.0"
description = "A Django-Ninja backend to specify FormKit schemas"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dependencies = [
    'Django>=3.1',
    'django-ninja',
    'django-ordered-model'
]
