# Generated by Django 5.1.3 on 2025-04-03 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("formkit_ninja", "0028_remove_publishedform_unique_active_schema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField()),
                ("form_data", models.JSONField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="formkit_ninja.publishedform",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
