# Generated by Django 5.1.3 on 2025-04-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissionsdemo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="form_data",
        ),
    ]
