# Generated by Django 5.1.3 on 2025-04-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissionsdemo", "0002_remove_submission_form_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
