# Generated by Django 5.1.3 on 2025-04-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissionsdemo", "0003_submission_deleted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-created_at"]},
        ),
    ]
