# Generated by Django 4.2.27 on 2026-02-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formkit_ninja', '0038_separatedsubmissionevent_submissionevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tf611',
            fields=[
                ('district', models.TextField(blank=True, null=True)),
                ('administrative_post', models.TextField(blank=True, null=True)),
                ('suco', models.TextField(blank=True, null=True)),
                ('aldeia', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('project_status', models.TextField(blank=True, null=True)),
                ('project_sector', models.TextField(blank=True, null=True)),
                ('project_sub_sector', models.TextField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('women_priority', models.TextField(blank=True, null=True)),
                ('number_of_households', models.IntegerField(blank=True, null=True)),
                ('no_of_women', models.IntegerField(blank=True, null=True)),
                ('no_of_men', models.IntegerField(blank=True, null=True)),
                ('no_of_pwd_male', models.IntegerField(blank=True, null=True)),
                ('no_of_pwd_female', models.IntegerField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='formkit_ninja.separatedsubmission')),
            ],
            options={
                'verbose_name': 'TF 6 1 1 Submission',
                'verbose_name_plural': 'TF 6 1 1 Submissions',
            },
        ),
        migrations.CreateModel(
            name='Tf611Repeaterprojectoutput',
            fields=[
                ('ordinality', models.IntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='formkit_ninja.separatedsubmission')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('woman_priority', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_outputs', to='partisipa.tf611')),
            ],
            options={
                'verbose_name': 'TF 6 1 1 Project Output',
                'verbose_name_plural': 'TF 6 1 1 Project Outputs',
                'ordering': ['parent', 'ordinality'],
            },
        ),
    ]
