# Generated by Django 4.2.27 on 2026-02-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formkit_ninja', '0037_alter_formkitschemanode_django_field_args_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainForm',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='formkit_ninja.separatedsubmission')),
                ('title', models.TextField(blank='True', null='True')),
                ('description', models.TextField(blank='True', null='True')),
            ],
        ),
        migrations.CreateModel(
            name='MainFormLineItems',
            fields=[
                ('ordinality', models.IntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='formkit_ninja.separatedsubmission')),
                ('item_name', models.TextField(blank='True', null='True')),
                ('quantity', models.IntegerField(blank='True', null='True')),
                ('price', models.IntegerField(blank='True', null='True')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='complex_app.mainform')),
            ],
        ),
    ]
