# Generated by Django 4.1.3 on 2023-01-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formkit_ninja",
            "0003_alter_formcomponents_options_formkitschemanode_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formkitschemanode",
            name="group",
            field=models.ManyToManyField(
                blank=True,
                through="formkit_ninja.Membership",
                to="formkit_ninja.formkitschemanode",
            ),
        ),
        migrations.CreateModel(
            name="NodeChildren",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="formkit_ninja.formkitschemanode",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"node_type": "$el"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formkit_ninja.formkitschemanode",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                through="formkit_ninja.NodeChildren",
                to="formkit_ninja.formkitschemanode",
            ),
        ),
    ]
