# Generated by Django 4.1.5 on 2023-04-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formkit_ninja", "0008_rename_new_values_formkitschemanode_node_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formcomponents",
            options={"ordering": ("schema", "order")},
        ),
        migrations.RenameField(
            model_name="formcomponents",
            old_name="schem",
            new_name="schema",
        ),
        migrations.RemoveField(
            model_name="formkitschema",
            name="name",
        ),
        migrations.RemoveField(
            model_name="formkitschemanode",
            name="help",
        ),
        migrations.RemoveField(
            model_name="formkitschemanode",
            name="label",
        ),
        migrations.RemoveField(
            model_name="formkitschemanode",
            name="placeholder",
        ),
        migrations.AddField(
            model_name="formcomponents",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="formcomponents",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formcomponents",
            name="key",
            field=models.CharField(
                default=1, help_text="Used as a human-readable label", max_length=1024, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formcomponents",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="formcomponents",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formkitschema",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="formkitschema",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formkitschema",
            name="key",
            field=models.SlugField(default="", max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formkitschema",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="formkitschema",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="additional_props",
            field=models.JSONField(blank=True, help_text="User space for additional, less used props", null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="admin_key",
            field=models.CharField(
                default="", help_text="Used as a human-readable label", max_length=1024, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="translation_context",
            field=models.CharField(
                blank=True,
                help_text="The gettext context to use to translate Options, label, placeholder and help text",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nodechildren",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="nodechildren",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nodechildren",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="nodechildren",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formcomponents",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="formkitschema",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="formkitschemanode",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Decribe the type of data / reason for this component",
                max_length=4000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formkitschemanode",
            name="node",
            field=models.JSONField(
                blank=True, help_text="A JSON representation of select parts of the FormKit schema", null=True
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                limit_choices_to={"node__formkit": "group"},
                on_delete=django.db.models.deletion.CASCADE,
                to="formkit_ninja.formkitschemanode",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="nodechildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="nodechildren",
            name="parent",
            field=models.ForeignKey(
                limit_choices_to={"node__node_type": "$el"},
                on_delete=django.db.models.deletion.CASCADE,
                to="formkit_ninja.formkitschemanode",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="field",
            field=models.ForeignKey(
                limit_choices_to={"node__formkit__in": ["select", "radio"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="formkit_ninja.formkitschemanode",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="option",
            name="label",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Translatable",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("object_id", models.UUIDField(editable=False)),
                ("language_code", models.CharField(editable=False, max_length=3)),
                (
                    "field",
                    models.CharField(
                        editable=False, help_text="The field on the generic model to translate", max_length=100
                    ),
                ),
                ("value", models.CharField(blank=True, editable=False, max_length=5000, null=True)),
                ("context", models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ("msgstr", models.CharField(help_text="The string", max_length=5000)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
