# Generated by Django 4.1.5 on 2023-04-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formkit_ninja", "0010_alter_formcomponents_id_alter_option_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formkitschemanode",
            old_name="admin_key",
            new_name="label",
        ),
    ]
