# Generated by Django 4.1.5 on 2023-04-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formkit_ninja", "0011_rename_admin_key_formkitschemanode_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formcomponents",
            old_name="key",
            new_name="label",
        ),
    ]
