# Generated by Django 4.1.5 on 2023-04-26 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("formkit_ninja", "0012_rename_key_formcomponents_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formcomponents",
            name="label",
            field=models.CharField(
                default=uuid.uuid4, help_text="Used as a human-readable label", max_length=1024, unique=True
            ),
        ),
    ]
