# Generated by Django 4.2.27 on 2026-01-16

import pgtrigger
from django.db import migrations


def forward(apps, schema_editor):
    FormKitSchemaNode = apps.get_model("formkit_ninja", "FormKitSchemaNode")

    with pgtrigger.ignore("formkit_ninja.FormKitSchemaNode:protect_node_updates"):
        for node in FormKitSchemaNode.objects.filter(additional_props__isnull=False).iterator():
            changed = False
            props = node.additional_props
            if not isinstance(props, dict):
                continue

            if "step" in props:
                node.step = str(props.pop("step"))
                changed = True

            if "addLabel" in props:
                node.add_label = props.pop("addLabel")
                changed = True

            if "upControl" in props:
                val = props.pop("upControl")
                if val is False or val == "false":
                    node.up_control = False
                    changed = True
                elif val is True or val == "true":
                    node.up_control = True
                    changed = True

            if "downControl" in props:
                val = props.pop("downControl")
                if val is False or val == "false":
                    node.down_control = False
                    changed = True
                elif val is True or val == "true":
                    node.down_control = True
                    changed = True

            if changed:
                node.additional_props = props
                node.save()


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0031_remove_formkitschemanode_insert_insert_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
