# Generated by Django 4.2.27 on 2026-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0033_remove_formkitschemanode_insert_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeGenerationConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formkit_type",
                    models.CharField(
                        db_index=True,
                        help_text='FormKit type (e.g., "text", "datepicker", "repeater")',
                        max_length=100,
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional: match specific node name (higher priority than formkit_type)",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "options_pattern",
                    models.CharField(
                        blank=True,
                        help_text='Optional: match if options starts with this pattern (e.g., "$ida(")',
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "pydantic_type",
                    models.CharField(
                        blank=True,
                        help_text='Override Pydantic type (e.g., "int", "str", "Decimal", "date")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "django_type",
                    models.CharField(
                        blank=True,
                        help_text='Override Django field type (e.g., "ForeignKey", "IntegerField", "DateField")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "django_args",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Django field arguments as JSON dict (e.g., {"null": true, "blank": true, "to": "app.Model"})',
                    ),
                ),
                (
                    "extra_imports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of import statements to add to generated files (e.g., ["from decimal import Decimal"])',
                    ),
                ),
                (
                    "validators",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validator strings (e.g., Pydantic field_validator decorators)",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Matching priority (higher = checked first). Use for fine-grained control when multiple configs might match.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Set to False to disable this configuration without deleting it"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Code generation config",
                "verbose_name_plural": "Code generation configs",
                "ordering": ["-priority", "formkit_type", "node_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="codegenerationconfig",
            constraint=models.UniqueConstraint(fields=("formkit_type", "node_name", "options_pattern"), name="unique_code_gen_config"),
        ),
    ]
