# Generated by Django 4.2.27 on 2026-02-01 17:53

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import formkit_ninja.form_submission.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formkit_ninja", "0034_codegenerationconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codegenerationconfig",
            name="priority",
            field=models.IntegerField(default=0, help_text="Matching priority (higher = checked first). Use for fine-grained control."),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "New Submission"), (2, "Rejected"), (3, "Verified"), (4, "Changes Requested")],
                        default=1,
                    ),
                ),
                (
                    "fields",
                    formkit_ninja.form_submission.models.SubmissionField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("form_type", models.CharField(help_text="The type of form used in the submission", max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeparatedSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "New Submission"), (2, "Rejected"), (3, "Verified"), (4, "Changes Requested")],
                        default=1,
                    ),
                ),
                ("fields", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("form_type", models.CharField(help_text="The type of form used in the submission", max_length=256)),
                (
                    "repeater_key",
                    models.CharField(blank=True, help_text="The field name in the original JSON document", max_length=256, null=True),
                ),
                (
                    "repeater_order",
                    models.IntegerField(blank=True, help_text="The original order of a repeater in the JSON", null=True),
                ),
                (
                    "repeater_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeater_set",
                        to="formkit_ninja.separatedsubmission",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The original submission.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formkit_ninja.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
