# Generated by Django 4.2.27 on 2026-02-02 02:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0035_alter_codegenerationconfig_priority_submission_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="update_update",
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="django_field_args",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Django field arguments as JSON dict (e.g., {"null": true, "blank": true})',
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="django_field_type",
            field=models.CharField(blank=True, help_text="Override Django field type", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="extra_imports",
            field=models.JSONField(
                blank=True, default=list, help_text='List of import statements (e.g., ["from decimal import Decimal"])'
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="pydantic_field_type",
            field=models.CharField(blank=True, help_text="Override Pydantic type", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="validators",
            field=models.JSONField(
                blank=True, default=list, help_text='List of validator strings (e.g., ["MinValueValidator(0)"])'
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanodeevent",
            name="django_field_args",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Django field arguments as JSON dict (e.g., {"null": true, "blank": true})',
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanodeevent",
            name="django_field_type",
            field=models.CharField(blank=True, help_text="Override Django field type", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanodeevent",
            name="extra_imports",
            field=models.JSONField(
                blank=True, default=list, help_text='List of import statements (e.g., ["from decimal import Decimal"])'
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanodeevent",
            name="pydantic_field_type",
            field=models.CharField(blank=True, help_text="Override Pydantic type", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formkitschemanodeevent",
            name="validators",
            field=models.JSONField(
                blank=True, default=list, help_text='List of validator strings (e.g., ["MinValueValidator(0)"])'
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="formkitschemanode",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_formkitschemanodeevent" ("add_label", "additional_props", "created", "created_by_id", "description", "django_field_args", "django_field_type", "down_control", "extra_imports", "icon", "id", "is_active", "label", "max", "min", "node", "node_type", "option_group_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protected", "pydantic_field_type", "readonly", "sections_schema", "step", "text_content", "title", "track_change", "up_control", "updated", "updated_by_id", "validators") VALUES (NEW."add_label", NEW."additional_props", NEW."created", NEW."created_by_id", NEW."description", NEW."django_field_args", NEW."django_field_type", NEW."down_control", NEW."extra_imports", NEW."icon", NEW."id", NEW."is_active", NEW."label", NEW."max", NEW."min", NEW."node", NEW."node_type", NEW."option_group_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."protected", NEW."pydantic_field_type", NEW."readonly", NEW."sections_schema", NEW."step", NEW."text_content", NEW."title", NEW."track_change", NEW."up_control", NEW."updated", NEW."updated_by_id", NEW."validators"); RETURN NULL;',
                    hash="96e0e78157816eb80f74fbe46e89ac3bd52d37cf",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_72c4c",
                    table="formkit_ninja_formkitschemanode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="formkitschemanode",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_formkitschemanodeevent" ("add_label", "additional_props", "created", "created_by_id", "description", "django_field_args", "django_field_type", "down_control", "extra_imports", "icon", "id", "is_active", "label", "max", "min", "node", "node_type", "option_group_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protected", "pydantic_field_type", "readonly", "sections_schema", "step", "text_content", "title", "track_change", "up_control", "updated", "updated_by_id", "validators") VALUES (NEW."add_label", NEW."additional_props", NEW."created", NEW."created_by_id", NEW."description", NEW."django_field_args", NEW."django_field_type", NEW."down_control", NEW."extra_imports", NEW."icon", NEW."id", NEW."is_active", NEW."label", NEW."max", NEW."min", NEW."node", NEW."node_type", NEW."option_group_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."protected", NEW."pydantic_field_type", NEW."readonly", NEW."sections_schema", NEW."step", NEW."text_content", NEW."title", NEW."track_change", NEW."up_control", NEW."updated", NEW."updated_by_id", NEW."validators"); RETURN NULL;',
                    hash="2a05fcc36214636defcc1fcea6d77fe61363e45a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d7c99",
                    table="formkit_ninja_formkitschemanode",
                    when="AFTER",
                ),
            ),
        ),
    ]
