# Generated by Django 4.2.27 on 2026-02-02 07:15

import uuid

import django.core.serializers.json
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import formkit_ninja.form_submission.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pghistory", "0007_auto_20250421_0444"),
        ("formkit_ninja", "0037_alter_formkitschemanode_django_field_args_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeparatedSubmissionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.UUIDField(default=uuid.uuid4, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "New Submission"), (2, "Rejected"), (3, "Verified"), (4, "Changes Requested")],
                        default=1,
                    ),
                ),
                ("fields", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("form_type", models.CharField(help_text="The type of form used in the submission", max_length=256)),
                (
                    "repeater_key",
                    models.CharField(blank=True, help_text="The field name in the original JSON document", max_length=256, null=True),
                ),
                (
                    "repeater_order",
                    models.IntegerField(blank=True, help_text="The original order of a repeater in the JSON", null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "New Submission"), (2, "Rejected"), (3, "Verified"), (4, "Changes Requested")],
                        default=1,
                    ),
                ),
                (
                    "fields",
                    formkit_ninja.form_submission.models.SubmissionField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("form_type", models.CharField(help_text="The type of form used in the submission", max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_order", "repeater_parent_id", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."repeater_key", NEW."repeater_order", NEW."repeater_parent_id", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="e47e175563b824eaf2bb3b5c21aa00c9ff45fe55",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_477cd",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_order", "repeater_parent_id", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."repeater_key", NEW."repeater_order", NEW."repeater_parent_id", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="3eb11ef74a7fcb1a3fba6f16ad647614efd30699",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8f1da",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="submission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_submissionevent" ("created", "fields", "form_type", "is_active", "key", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."is_active", NEW."key", _pgh_attach_context(), NOW(), \'insert\', NEW."key", NEW."status", NEW."updated", NEW."user_id"); RETURN NULL;',
                    hash="2b445748524343941efece9315567d99c1430634",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_f5ccf",
                    table="formkit_ninja_submission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="submission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_submissionevent" ("created", "fields", "form_type", "is_active", "key", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."is_active", NEW."key", _pgh_attach_context(), NOW(), \'update\', NEW."key", NEW."status", NEW."updated", NEW."user_id"); RETURN NULL;',
                    hash="3da6d322ed60d6a34b03b297b7abe5a4d75c8341",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_511e9",
                    table="formkit_ninja_submission",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="submissionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="submissionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="formkit_ninja.submission",
            ),
        ),
        migrations.AddField(
            model_name="submissionevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="separatedsubmissionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="separatedsubmissionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="formkit_ninja.separatedsubmission",
            ),
        ),
        migrations.AddField(
            model_name="separatedsubmissionevent",
            name="repeater_parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="formkit_ninja.separatedsubmission",
            ),
        ),
        migrations.AddField(
            model_name="separatedsubmissionevent",
            name="submission",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="The original submission.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="formkit_ninja.submission",
            ),
        ),
        migrations.AddField(
            model_name="separatedsubmissionevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
