# Generated by Django 4.2.27 on 2026-02-03 16:31

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formkit_ninja", "0039_remove_formkitschemanode_insert_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submission", models.UUIDField()),
                ("file", models.FileField(upload_to="submission_files")),
                ("comment", models.TextField()),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SeparatedSubmissionImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField()),
                ("message", models.TextField()),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="formkit_ninja.separatedsubmission")),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="submissionfile",
            trigger=pgtrigger.compiler.Trigger(
                name="soft_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "formkit_ninja_submissionfile" SET deleted = True WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="0da026dc0417eb75e8262a08153338061a7305cb",
                    operation="DELETE",
                    pgid="pgtrigger_soft_delete_aadaa",
                    table="formkit_ninja_submissionfile",
                    when="BEFORE",
                ),
            ),
        ),
    ]
