# Generated by Django 4.2.27 on 2026-06-10 06:48

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0042_formkitschemanode_list_filter"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="update_update",
        ),
        migrations.AddField(
            model_name="formkitschemanode",
            name="code_scheme",
            field=models.CharField(
                blank=True,
                choices=[("pnds", "PNDS (zTable IDs — current)"), ("estrada", "Estrada (timor-locations pre-INTL pcodes)"), ("intl2024", "intl2024 (INTL string pcodes)")],
                help_text="Metadata tag for the geographic pcode scheme this input emits (e.g. Suco/Postu/Munisipiu values). Read by downstream consumers such as partisipa-import; formkit-ninja does not validate or translate the values themselves.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formkitschemanodeevent",
            name="code_scheme",
            field=models.CharField(
                blank=True,
                choices=[("pnds", "PNDS (zTable IDs — current)"), ("estrada", "Estrada (timor-locations pre-INTL pcodes)"), ("intl2024", "intl2024 (INTL string pcodes)")],
                help_text="Metadata tag for the geographic pcode scheme this input emits (e.g. Suco/Postu/Munisipiu values). Read by downstream consumers such as partisipa-import; formkit-ninja does not validate or translate the values themselves.",
                max_length=32,
                null=True,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="formkitschemanode",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_formkitschemanodeevent" ("add_label", "additional_props", "code_scheme", "created", "created_by_id", "description", "django_field_args", "django_field_positional_args", "django_field_type", "down_control", "extra_imports", "icon", "id", "is_active", "label", "list_filter", "max", "min", "node", "node_type", "option_group_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protected", "pydantic_field_type", "readonly", "sections_schema", "step", "text_content", "title", "track_change", "up_control", "updated", "updated_by_id", "validators") VALUES (NEW."add_label", NEW."additional_props", NEW."code_scheme", NEW."created", NEW."created_by_id", NEW."description", NEW."django_field_args", NEW."django_field_positional_args", NEW."django_field_type", NEW."down_control", NEW."extra_imports", NEW."icon", NEW."id", NEW."is_active", NEW."label", NEW."list_filter", NEW."max", NEW."min", NEW."node", NEW."node_type", NEW."option_group_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."protected", NEW."pydantic_field_type", NEW."readonly", NEW."sections_schema", NEW."step", NEW."text_content", NEW."title", NEW."track_change", NEW."up_control", NEW."updated", NEW."updated_by_id", NEW."validators"); RETURN NULL;',
                    hash="f1c63d16eac3a47e69e99b9139042e29dfe77d36",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_72c4c",
                    table="formkit_ninja_formkitschemanode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="formkitschemanode",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_formkitschemanodeevent" ("add_label", "additional_props", "code_scheme", "created", "created_by_id", "description", "django_field_args", "django_field_positional_args", "django_field_type", "down_control", "extra_imports", "icon", "id", "is_active", "label", "list_filter", "max", "min", "node", "node_type", "option_group_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protected", "pydantic_field_type", "readonly", "sections_schema", "step", "text_content", "title", "track_change", "up_control", "updated", "updated_by_id", "validators") VALUES (NEW."add_label", NEW."additional_props", NEW."code_scheme", NEW."created", NEW."created_by_id", NEW."description", NEW."django_field_args", NEW."django_field_positional_args", NEW."django_field_type", NEW."down_control", NEW."extra_imports", NEW."icon", NEW."id", NEW."is_active", NEW."label", NEW."list_filter", NEW."max", NEW."min", NEW."node", NEW."node_type", NEW."option_group_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."protected", NEW."pydantic_field_type", NEW."readonly", NEW."sections_schema", NEW."step", NEW."text_content", NEW."title", NEW."track_change", NEW."up_control", NEW."updated", NEW."updated_by_id", NEW."validators"); RETURN NULL;',
                    hash="b235a3efcf5b151e2b55767023c943dee28517b0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d7c99",
                    table="formkit_ninja_formkitschemanode",
                    when="AFTER",
                ),
            ),
        ),
    ]
