# Generated by Django 4.2.27 on 2026-08-03 13:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

# One-time reconciliation of any SeparatedSubmission.status rows that drifted from
# their root Submission.status before this trigger existed (status changes that
# bypassed save() — bulk .update(), restores, raw SQL). Idempotent: only touches
# rows that are actually out of sync. Runs after the trigger so the mirror is both
# corrected now and kept correct going forward.
BACKFILL_SQL = """
UPDATE formkit_ninja_separatedsubmission s
SET status = sub.status
FROM formkit_ninja_submission sub
WHERE s.submission_id = sub.key
  AND s.status IS DISTINCT FROM sub.status;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0045_strip_stale_additional_props"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="submission",
            trigger=pgtrigger.compiler.Trigger(
                name="sync_separated_submission_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func="\n                    UPDATE formkit_ninja_separatedsubmission\n                    SET status = NEW.status\n                    WHERE submission_id = NEW.key\n                      AND status IS DISTINCT FROM NEW.status;\n                    RETURN NEW;\n                    ",
                    hash="03c486e322810aced031445a92f5190753713a99",
                    operation="UPDATE",
                    pgid="pgtrigger_sync_separated_submission_status_d5cd4",
                    table="formkit_ninja_submission",
                    when="AFTER",
                ),
            ),
        ),
        migrations.RunSQL(sql=BACKFILL_SQL, reverse_sql=migrations.RunSQL.noop),
    ]
