# Generated by Django 4.2.27 on 2026-08-09 14:05

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0047_fix_group_order_trigger_before_update"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="formcomponents",
            name="order_on_update_option",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="nodechildren",
            name="order_on_update_option",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="option",
            name="order_on_update_option",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="formcomponents",
            trigger=pgtrigger.compiler.Trigger(
                name="order_on_update_option",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (pg_trigger_depth() = 0)",
                    func='\n                -- Do not allow a "null" value\n                -- This stops Django from dumbly updating\n                -- which can break the trigger\n                if NEW."order" IS NULL then\n                    NEW."order" = OLD."order";\n                end if;\n                -- ... unless the stored order was NULL too: append instead.\n                if NEW."order" IS NULL then\n                    NEW."order" = (\n                        SELECT coalesce(max("order"), 0) + 1\n                        FROM formkit_ninja_formcomponents\n                        WHERE "schema_id" = NEW."schema_id"\n                        AND "id" <> NEW."id"\n                    );\n                end if;\n                if OLD."order" IS NULL\n                or NEW."schema_id" IS DISTINCT FROM OLD."schema_id" then\n                    -- An arrival: make room at the destination.\n                    update formkit_ninja_formcomponents\n                    set "order" = "order"+ 1\n                    where "order" >= NEW."order"\n                    and "schema_id" = NEW."schema_id"\n                    and "id" <> NEW."id";\n                    -- A departure, but only if the row held a slot in a group\n                    -- it has now left.\n                    if OLD."order" IS NOT NULL\n                    and NEW."schema_id" IS DISTINCT FROM OLD."schema_id" then\n                        update formkit_ninja_formcomponents\n                        set "order" = "order"- 1\n                        where "order" > OLD."order"\n                        and "schema_id" = OLD."schema_id"\n                        and "id" <> NEW."id";\n                    end if;\n                elsif NEW."order" > OLD."order" then\n                    update formkit_ninja_formcomponents\n                    set "order" = "order"- 1\n                    where "order" <= NEW."order"\n                    and "order" > OLD."order"\n                    and "schema_id" = NEW."schema_id"\n                    and "id" <> NEW."id";\n                else\n                    update formkit_ninja_formcomponents\n                    set "order" = "order"+ 1\n                    where "order" >= NEW."order"\n                    and "order" < OLD."order"\n                    and "schema_id" = NEW."schema_id"\n                    and "id" <> NEW."id";\n                end if;\n                RETURN NEW;\n        ',
                    hash="ce92dcdb31cdc5ad4dd714e6e8c6736cc24502e2",
                    operation="UPDATE",
                    pgid="pgtrigger_order_on_update_option_a5326",
                    table="formkit_ninja_formcomponents",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="nodechildren",
            trigger=pgtrigger.compiler.Trigger(
                name="order_on_update_option",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (pg_trigger_depth() = 0)",
                    func='\n                -- Do not allow a "null" value\n                -- This stops Django from dumbly updating\n                -- which can break the trigger\n                if NEW."order" IS NULL then\n                    NEW."order" = OLD."order";\n                end if;\n                -- ... unless the stored order was NULL too: append instead.\n                if NEW."order" IS NULL then\n                    NEW."order" = (\n                        SELECT coalesce(max("order"), 0) + 1\n                        FROM formkit_ninja_nodechildren\n                        WHERE "parent_id" = NEW."parent_id"\n                        AND "id" <> NEW."id"\n                    );\n                end if;\n                if OLD."order" IS NULL\n                or NEW."parent_id" IS DISTINCT FROM OLD."parent_id" then\n                    -- An arrival: make room at the destination.\n                    update formkit_ninja_nodechildren\n                    set "order" = "order"+ 1\n                    where "order" >= NEW."order"\n                    and "parent_id" = NEW."parent_id"\n                    and "id" <> NEW."id";\n                    -- A departure, but only if the row held a slot in a group\n                    -- it has now left.\n                    if OLD."order" IS NOT NULL\n                    and NEW."parent_id" IS DISTINCT FROM OLD."parent_id" then\n                        update formkit_ninja_nodechildren\n                        set "order" = "order"- 1\n                        where "order" > OLD."order"\n                        and "parent_id" = OLD."parent_id"\n                        and "id" <> NEW."id";\n                    end if;\n                elsif NEW."order" > OLD."order" then\n                    update formkit_ninja_nodechildren\n                    set "order" = "order"- 1\n                    where "order" <= NEW."order"\n                    and "order" > OLD."order"\n                    and "parent_id" = NEW."parent_id"\n                    and "id" <> NEW."id";\n                else\n                    update formkit_ninja_nodechildren\n                    set "order" = "order"+ 1\n                    where "order" >= NEW."order"\n                    and "order" < OLD."order"\n                    and "parent_id" = NEW."parent_id"\n                    and "id" <> NEW."id";\n                end if;\n                RETURN NEW;\n        ',
                    hash="8c1f3c186d470ee600336cebb72f1b15e9b7cef6",
                    operation="UPDATE",
                    pgid="pgtrigger_order_on_update_option_44228",
                    table="formkit_ninja_nodechildren",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="option",
            trigger=pgtrigger.compiler.Trigger(
                name="order_on_update_option",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (pg_trigger_depth() = 0)",
                    func='\n                -- Do not allow a "null" value\n                -- This stops Django from dumbly updating\n                -- which can break the trigger\n                if NEW."order" IS NULL then\n                    NEW."order" = OLD."order";\n                end if;\n                -- ... unless the stored order was NULL too: append instead.\n                if NEW."order" IS NULL then\n                    NEW."order" = (\n                        SELECT coalesce(max("order"), 0) + 1\n                        FROM formkit_ninja_option\n                        WHERE "group_id" = NEW."group_id"\n                        AND "id" <> NEW."id"\n                    );\n                end if;\n                if OLD."order" IS NULL\n                or NEW."group_id" IS DISTINCT FROM OLD."group_id" then\n                    -- An arrival: make room at the destination.\n                    update formkit_ninja_option\n                    set "order" = "order"+ 1\n                    where "order" >= NEW."order"\n                    and "group_id" = NEW."group_id"\n                    and "id" <> NEW."id";\n                    -- A departure, but only if the row held a slot in a group\n                    -- it has now left.\n                    if OLD."order" IS NOT NULL\n                    and NEW."group_id" IS DISTINCT FROM OLD."group_id" then\n                        update formkit_ninja_option\n                        set "order" = "order"- 1\n                        where "order" > OLD."order"\n                        and "group_id" = OLD."group_id"\n                        and "id" <> NEW."id";\n                    end if;\n                elsif NEW."order" > OLD."order" then\n                    update formkit_ninja_option\n                    set "order" = "order"- 1\n                    where "order" <= NEW."order"\n                    and "order" > OLD."order"\n                    and "group_id" = NEW."group_id"\n                    and "id" <> NEW."id";\n                else\n                    update formkit_ninja_option\n                    set "order" = "order"+ 1\n                    where "order" >= NEW."order"\n                    and "order" < OLD."order"\n                    and "group_id" = NEW."group_id"\n                    and "id" <> NEW."id";\n                end if;\n                RETURN NEW;\n        ',
                    hash="96ec542b1e100450c03a78991f2c0df5b3ebcf11",
                    operation="UPDATE",
                    pgid="pgtrigger_order_on_update_option_417cb",
                    table="formkit_ninja_option",
                    when="BEFORE",
                ),
            ),
        ),
    ]
