# Generated by Django 4.2.27 on 2026-06-19 02:51

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0048_backfill_pghistory_to_streams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formkitschemanodeevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="formkitschemanodeevent",
            name="option_group",
        ),
        migrations.RemoveField(
            model_name="formkitschemanodeevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="formkitschemanodeevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="formkitschemanodeevent",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="repeater_parent",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="submissionevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="submissionevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="submissionevent",
            name="user",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="formkitschemanode",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="submission",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="submission",
            name="update_update",
        ),
        migrations.DeleteModel(
            name="FormKitSchemaNodeEvent",
        ),
        migrations.DeleteModel(
            name="SeparatedSubmissionEvent",
        ),
        migrations.DeleteModel(
            name="SubmissionEvent",
        ),
    ]
