# Generated by Django 4.2.27 on 2026-06-19 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formkit_ninja", "0048_fix_group_order_trigger_null_and_cross_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flag",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for triaging/resolving this flag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("assigned_at__isnull", True), ("assigned_to__isnull", True)),
                    models.Q(("assigned_at__isnull", False), ("assigned_to__isnull", False)),
                    _connector="OR",
                ),
                name="flag_assigned_to_and_at_together",
            ),
        ),
    ]
