# Generated by Django 4.2.27 on 2026-08-14 12:42

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0049_flag_assigned_at_flag_assigned_to"),
    ]

    operations = [
        # NodeChildren.track_change moves from its own sequence
        # (nodechildren_change_id) onto the node sequence, so link rows and the
        # nodes they join become one comparable change stream (issue #68).
        #
        # Existing rows keep their old-sequence values and are NOT re-stamped:
        # re-stamping would mark every relation as changed and force a full
        # re-fetch on every client. That is safe only if the merged sequence is
        # guaranteed to issue values above every value already stored, which is
        # what this setval establishes. Without it, if nodechildren_change_id
        # happened to be ahead of the node sequence, a stale-high stored value
        # would dominate the published latest_change and clients would miss
        # updates until the node sequence caught up.
        migrations.RunSQL(
            sql="""
                SELECT setval(
                    'formkitschemanode_change_id',
                    GREATEST(
                        (SELECT last_value FROM formkitschemanode_change_id),
                        COALESCE((SELECT max(track_change) FROM formkit_ninja_nodechildren), 0)
                    )
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="nodechildren",
            name="version_on_update",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="nodechildren",
            trigger=pgtrigger.compiler.Trigger(
                name="version_on_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.\"track_change\" = nextval('formkitschemanode_change_id'); RETURN NEW;",
                    hash="9f7093e580720090161f6174b4f938378e185b39",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_version_on_update_9c530",
                    table="formkit_ninja_nodechildren",
                    when="BEFORE",
                ),
            ),
        ),
    ]
