# Generated by Django 4.2.27 on 2026-09-04 12:32

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0050_track_deletes"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="separatedsubmission",
            name="repeater_rank",
            field=models.TextField(blank=True, db_collation="C", help_text="Fractional index position of this repeater row within its sibling group", null=True),
        ),
        migrations.AddField(
            model_name="separatedsubmissionevent",
            name="repeater_rank",
            field=models.TextField(blank=True, db_collation="C", help_text="Fractional index position of this repeater row within its sibling group", null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_order", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."repeater_key", NEW."repeater_order", NEW."repeater_parent_id", NEW."repeater_rank", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="5860a967fcaba82f0141945e977090c8444fe64b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_477cd",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_order", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."repeater_key", NEW."repeater_order", NEW."repeater_parent_id", NEW."repeater_rank", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="1dedd4705ad69b93032e7b3def018848c8cbe9cb",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8f1da",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_order", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (OLD."created", OLD."fields", OLD."form_type", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."repeater_key", OLD."repeater_order", OLD."repeater_parent_id", OLD."repeater_rank", OLD."status", OLD."submission_id", OLD."user_id"); RETURN NULL;',
                    hash="7771dac48f7e583ea6f089b761046d87f7a25304",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_9c265",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
    ]
