"""Drop ``repeater_order`` (#74).

The column held the rank's position within its sibling group, counted — so removing it
is a change of representation, not a loss, and ``with_repeater_order()`` computes the
same number on demand.

That is only true if every row has a rank, so the migration checks before it drops. The
seeding command lives in the previous release: an installation that arrives here with
unranked rows must go back to it, because after this migration there is nothing left to
seed *from*.
"""

# Generated by Django 4.2.27 on 2026-09-04 13:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


def refuse_unless_every_row_is_ranked(apps, schema_editor):
    """Block the drop while any repeater row would lose its position.

    Two failures, reported separately because the fixes differ:

    * **unranked** — the seed has not run, or has not covered these rows. Recoverable,
      on the previous release, with ``manage.py backfill_repeater_ranks``.
    * **disagreeing** — the row has a rank, but it puts the row somewhere other than
      the stored index. Dropping would silently reorder someone's data. This one needs
      looking at, not re-running.

    Deliberately not a warning. A migration that prints and proceeds is a migration
    whose output scrolls past in a deploy log.
    """
    SeparatedSubmission = apps.get_model("formkit_ninja", "SeparatedSubmission")

    rows = (
        SeparatedSubmission.objects.filter(repeater_parent__isnull=False)
        .order_by("repeater_parent_id", "repeater_key", "repeater_rank", "pk")
        .values_list("pk", "repeater_parent_id", "repeater_key", "repeater_order", "repeater_rank")
    )

    unranked = []
    groups = {}
    for pk, parent_id, repeater_key, order, rank in rows.iterator(chunk_size=2000):
        if not rank:
            unranked.append(pk)
        groups.setdefault((parent_id, repeater_key), []).append((pk, order))

    # The query is already in rank order, so a group's stored indices must come back
    # ascending. Compared against their own sorted form rather than `range(len(members))`,
    # so a legitimately sparse index (0, 3, 7) is not read as a disagreement — the column
    # was nullable and unconstrained, and gaps in it were never a fault.
    #
    # NULL indices are dropped before comparing rather than sorted among the rest: a row
    # with no index has no opinion about the order, and including it made a group of
    # (NULL, 1) compare a 2-element list against a 1-element one and always fail.
    def in_ascending_order(members) -> bool:
        present = [order for _pk, order in members if order is not None]
        return present == sorted(present)

    disagreeing = [group for group, members in groups.items() if not in_ascending_order(members)]

    if not unranked and not disagreeing:
        return

    problems = []
    if unranked:
        problems.append(f"{len(unranked)} repeater row(s) have no rank (first: {unranked[0]})")
    if disagreeing:
        problems.append(f"{len(disagreeing)} sibling group(s) are ordered differently by rank than by repeater_order (first: {disagreeing[0]})")

    raise RuntimeError(
        "Refusing to drop repeater_order: " + "; ".join(problems) + ". Roll back to the previous release, run `manage.py backfill_repeater_ranks` "
        "and then `manage.py backfill_repeater_ranks --verify`, and migrate again. After "
        "this migration there is nothing left to seed the ranks from."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0051_separatedsubmission_repeater_rank"),
    ]

    operations = [
        migrations.RunPython(
            refuse_unless_every_row_is_ranked,
            # Reversing only restores the column; it cannot restore the values, which is
            # why the forward direction refuses rather than repairs.
            migrations.RunPython.noop,
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="delete_delete",
        ),
        migrations.RemoveField(
            model_name="separatedsubmission",
            name="repeater_order",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="repeater_order",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."repeater_key", NEW."repeater_parent_id", NEW."repeater_rank", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="9c6c40d4419224df81e410720cc7b13465a947f0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_477cd",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."repeater_key", NEW."repeater_parent_id", NEW."repeater_rank", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="9b99522d16f1c8907ee9e839dd43908552eddfcd",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8f1da",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (OLD."created", OLD."fields", OLD."form_type", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."repeater_key", OLD."repeater_parent_id", OLD."repeater_rank", OLD."status", OLD."submission_id", OLD."user_id"); RETURN NULL;',
                    hash="126f907cf9119e1725d7fa7f37c3dca6d7b0a033",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_9c265",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
    ]
