"""Drop ``repeater_order`` (#74).

The column held the rank's position within its sibling group, counted — so removing it is a
change of representation, not a loss, and ``with_repeater_order()`` computes the same number
on demand.

That is only true if every row has a rank, so this migration **seeds the ones that do not**
and then checks its work before dropping. Until 4.1.0 it refused instead, and the seeding
lived in the previous release — which meant every installation deployed twice for an
ordering constraint one migration can satisfy on its own. What still refuses is a group the
seeding cannot honestly resolve: see ``seed_then_refuse_if_the_order_would_change``.

The triggers come off **before** the seed rather than after it. They are removed here anyway
so the column can be dropped from the history table, and taking them off first means filling
in a position nobody has read yet does not write a history event per row saying nothing
happened.
"""

# Generated by Django 4.2.27 on 2026-09-04 13:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db.models import F

from formkit_ninja.fracrank import keys_between


def seed_then_refuse_if_the_order_would_change(apps, schema_editor):
    """Give every repeater row a rank, then block the drop if one would still lose its place.

    Three states, and only two of them stop the migration, because only two of them need a
    person:

    * **no rank at all, across a whole sibling group** — an *absence*, and the information
      needed to fill it is in the column about to be dropped. Seeded. Until 4.1.0 this
      refused and sent you back a release to run ``manage.py backfill_repeater_ranks``,
      which meant every installation deployed twice: once to seed, once to drop. Nothing
      about the seeding needed a separate deployment — it needed to happen *before this
      line*, which is where it now is.
    * **a rank on some rows of a group and not others** — an interrupted seed, or a save
      that landed mid-run. Filling the gaps and ignoring them both produce an order nobody
      chose, so this refuses and names the group.
    * **a rank that disagrees with the stored index** — a *contradiction*. Seeding cannot
      resolve it; the two sources disagree about the answer and picking one silently would
      reorder somebody's data. Refuses.

    Deliberately not a warning. A migration that prints and proceeds is a migration whose
    output scrolls past in a deploy log.

    Seeding inside a migration is the one thing here that a migration is usually wrong to
    do. It is justified by the alternative rather than by taste: the seed reads
    ``repeater_order``, this migration removes it, and no release after this one can do the
    work. The choice was never "migration or command" — it was "one deployment or two".
    """
    SeparatedSubmission = apps.get_model("formkit_ninja", "SeparatedSubmission")

    # `repeater_order` is nullable and Postgres sorts NULLs last ascending; `pk` breaks the
    # remaining ties so the seeded order is deterministic rather than heap order. The same
    # rule `compose()` and `in_document_order()` apply.
    rows = (
        SeparatedSubmission.objects.filter(repeater_parent__isnull=False)
        .order_by("repeater_parent_id", "repeater_key", F("repeater_order").asc(nulls_last=True), "pk")
        .values_list("pk", "repeater_parent_id", "repeater_key", "repeater_order", "repeater_rank")
    )

    groups: dict = {}
    for pk, parent_id, repeater_key, order, rank in rows.iterator(chunk_size=2000):
        groups.setdefault((parent_id, repeater_key), []).append((pk, order, rank))

    pending = []
    part_ranked = set()
    for group, members in groups.items():
        held = [rank for _pk, _order, rank in members]
        if any(held):
            # Something already has an opinion about this group's order. Covering the whole
            # group is fine — it is judged below like any other. Covering part of it is not.
            if not all(held):
                part_ranked.add(group)
            continue
        for (pk, _order, _rank), key in zip(members, keys_between(None, None, len(members))):
            pending.append(SeparatedSubmission(pk=pk, repeater_rank=key))

    for start in range(0, len(pending), 2000):
        # `bulk_update` writes the column without loading or saving the rows, so no
        # `post_save` fires and no downstream projection is rebuilt. Filling in a position
        # nobody has read yet must not look like every row being edited.
        #
        # That is only true of Django signals, which is why the pghistory triggers are
        # removed above this rather than below it: they are `WHEN (OLD.* IS DISTINCT FROM
        # NEW.*)`, so with them live this would write one history event per row recording
        # that a migration filled in a rank — on a database upgrading from before 3.4.0,
        # that is a history row for every repeater row it has, inside the transaction that
        # also takes the lock to drop a column.
        SeparatedSubmission.objects.bulk_update(pending[start : start + 2000], ["repeater_rank"])

    minted = {obj.pk: obj.repeater_rank for obj in pending}

    # Judge the ordering in **rank** order — the order rows will be in once the index is
    # gone, and so the only order worth checking. This is NOT the sequence the groups were
    # read in: they were read by `repeater_order` so the seeding could mint keys in that
    # sequence, and re-reading them that way here would compare a list against its own
    # sorted form and pass unconditionally. The first draft of 4.1.0 did exactly that, and
    # `test_it_refuses_when_the_rank_orders_a_group_differently` is what caught it.
    #
    # Stored indices must come back ascending. Compared against their own sorted form rather
    # than `range(len(members))`, so a legitimately sparse index (0, 3, 7) is not read as a
    # disagreement — the column was nullable and unconstrained, and gaps in it were never a
    # fault. NULL indices are dropped before comparing rather than sorted among the rest: a
    # row with no index has no opinion about the order, and including it made a group of
    # (NULL, 1) compare a 2-element list against a 1-element one and always fail.
    #
    # Only groups that are wholly seeded or wholly ranked reach here — part-ranked ones are
    # excluded below — so every row has a key and there is no missing-rank case to sort around.
    def in_ascending_order(members) -> bool:
        by_rank = sorted(members, key=lambda m: (minted.get(m[0]) or m[2], str(m[0])))
        present = [order for _pk, order, _rank in by_rank if order is not None]
        return present == sorted(present)

    disagreeing = [group for group, members in groups.items() if group not in part_ranked and not in_ascending_order(members)]

    if not part_ranked and not disagreeing:
        return

    problems = []
    if part_ranked:
        problems.append(
            f"{len(part_ranked)} sibling group(s) hold a rank on some rows and not others "
            f"(first: {sorted(part_ranked, key=str)[0]}), which is an interrupted seed or a save "
            "that landed mid-run — filling the gaps would produce an order nobody chose. Note "
            "`backfill_repeater_ranks` on 3.4.x will NOT fix this: it skips a group that already "
            "holds any rank, for the same reason. Decide per group — clear repeater_rank across "
            "the group so this migration can seed it whole, or set the missing ranks yourself to "
            "match repeater_order"
        )
    if disagreeing:
        problems.append(f"{len(disagreeing)} sibling group(s) are ordered differently by rank than by repeater_order (first: {disagreeing[0]})")

    raise RuntimeError(
        "Refusing to drop repeater_order: " + "; ".join(problems) + ". A group with no ranks at all is seeded by this migration and is not what stopped "
        "it; what is left needs looking at rather than re-running. Nothing has been changed by "
        "this attempt — the migration is transactional, so the database is exactly as it was."
    )


class Migration(migrations.Migration):
    #: Explicit, because the refusal below promises an operator that "nothing has been
    #: changed by this attempt". Before 4.1.0 that was trivially true — the step only read.
    #: It now writes before it raises, so the promise rests entirely on this being atomic,
    #: and `atomic = False` is a natural thing to reach for if the seed is ever felt to hold
    #: locks too long. Pinned by `test_the_migration_is_atomic`.
    atomic = True

    dependencies = [
        ("formkit_ninja", "0051_separatedsubmission_repeater_rank"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="separatedsubmission",
            name="delete_delete",
        ),
        migrations.RunPython(
            seed_then_refuse_if_the_order_would_change,
            # Reversing only restores the column; it cannot restore the values, which is
            # why the forward direction refuses rather than repairs.
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="separatedsubmission",
            name="repeater_order",
        ),
        migrations.RemoveField(
            model_name="separatedsubmissionevent",
            name="repeater_order",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."repeater_key", NEW."repeater_parent_id", NEW."repeater_rank", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="9c6c40d4419224df81e410720cc7b13465a947f0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_477cd",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (NEW."created", NEW."fields", NEW."form_type", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."repeater_key", NEW."repeater_parent_id", NEW."repeater_rank", NEW."status", NEW."submission_id", NEW."user_id"); RETURN NULL;',
                    hash="9b99522d16f1c8907ee9e839dd43908552eddfcd",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8f1da",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="separatedsubmission",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "formkit_ninja_separatedsubmissionevent" ("created", "fields", "form_type", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "repeater_key", "repeater_parent_id", "repeater_rank", "status", "submission_id", "user_id") VALUES (OLD."created", OLD."fields", OLD."form_type", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."repeater_key", OLD."repeater_parent_id", OLD."repeater_rank", OLD."status", OLD."submission_id", OLD."user_id"); RETURN NULL;',
                    hash="126f907cf9119e1725d7fa7f37c3dca6d7b0a033",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_9c265",
                    table="formkit_ninja_separatedsubmission",
                    when="AFTER",
                ),
            ),
        ),
    ]
