# Generated by Django 4.2.27 on 2026-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0052_drop_repeater_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="separatedsubmissionimport",
            index=models.Index(fields=["submission", "-created", "-id"], name="sepsubimport_latest_idx"),
        ),
    ]
