# Generated by Django 4.2.27 on 2026-09-21 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0054_nodechildren_version_on_node_sequence"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="flag",
            name="flag_unresolved_by_sepsub_idx",
        ),
        migrations.AddField(
            model_name="flag",
            name="request_key",
            field=models.CharField(blank=True, help_text="The consumer's id for the request this flag is about, when there is one", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="flag",
            name="separated_submission",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="quality_flags", to="formkit_ninja.separatedsubmission"),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(condition=models.Q(("resolved_at__isnull", True), ("separated_submission__isnull", False)), fields=["separated_submission"], name="flag_unresolved_by_sepsub_idx"),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["request_key"], name="flag_request_key_idx"),
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=models.CheckConstraint(
                check=models.Q(("separated_submission__isnull", False), models.Q(("request_key__gt", ""), ("request_key__isnull", False)), _connector="OR"),
                name="flag_has_submission_or_request",
                violation_error_message="A flag needs a separated submission, a request key, or both.",
            ),
        ),
    ]
