# Generated by Django 4.2.27 on 2026-09-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0055_flag_request_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="params",
            field=models.JSONField(blank=True, default=dict, help_text="Values the message refers to, keyed by the rule that wrote the flag"),
        ),
    ]
