# Generated by Django 4.2.27 on 2026-09-21 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0056_flag_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("form_type", models.CharField(help_text="The form this version belongs to, spelled as on Submission.form_type", max_length=128)),
                ("version", models.PositiveIntegerField(help_text="2 for the first mint; a form never minted is at 1")),
                ("migration", models.CharField(help_text="The migration that minted this version", max_length=255)),
                ("minted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["form_type", "version"],
            },
        ),
        migrations.AddConstraint(
            model_name="schemaversion",
            constraint=models.UniqueConstraint(fields=("form_type", "version"), name="schemaversion_one_row_per_version"),
        ),
        migrations.AddConstraint(
            model_name="schemaversion",
            constraint=models.CheckConstraint(check=models.Q(("version__gte", 2)), name="schemaversion_minted_from_2"),
        ),
    ]
