# Generated by Django 4.2.27 on 2026-09-23 02:26

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

#: Give every group that already has a child list a version to start from.
#:
#: Without this, a group with children but no row would be missing from
#: ``list-related-nodes`` until somebody edited it — every device would keep
#: whatever it last heard, and nothing would say so. The value is the greatest
#: version already present in the group's link rows, so no client is told a
#: change happened that did not: a device whose watermark is at or above that
#: value still sees nothing new.
SEED_EXISTING_GROUPS = """
    INSERT INTO formkit_ninja_nodechildrenchange (parent_id, track_change)
    SELECT parent_id, MAX(COALESCE(track_change, 0))
    FROM formkit_ninja_nodechildren
    GROUP BY parent_id
    ON CONFLICT (parent_id) DO NOTHING;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("formkit_ninja", "0057_schemaversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeChildrenChange",
            fields=[
                (
                    "parent",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="child_list_change", serialize=False, to="formkit_ninja.formkitschemanode"),
                ),
                ("track_change", models.BigIntegerField()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="nodechildren",
            trigger=pgtrigger.compiler.Trigger(
                name="version_child_list",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                IF TG_OP <> 'INSERT' THEN\n                    \n        INSERT INTO formkit_ninja_nodechildrenchange (parent_id, track_change)\n        VALUES (OLD.\"parent_id\", nextval('formkitschemanode_change_id'))\n        ON CONFLICT (parent_id) DO UPDATE SET track_change = EXCLUDED.track_change;\n    \n                END IF;\n                IF TG_OP <> 'DELETE' AND (TG_OP = 'INSERT' OR NEW.\"parent_id\" IS DISTINCT FROM OLD.\"parent_id\") THEN\n                    \n        INSERT INTO formkit_ninja_nodechildrenchange (parent_id, track_change)\n        VALUES (NEW.\"parent_id\", nextval('formkitschemanode_change_id'))\n        ON CONFLICT (parent_id) DO UPDATE SET track_change = EXCLUDED.track_change;\n    \n                END IF;\n                RETURN NULL;\n            ",
                    hash="252b7550b7e2c868a9e08567a792f7cdbcd80235",
                    operation="INSERT OR UPDATE OR DELETE",
                    pgid="pgtrigger_version_child_list_9945b",
                    table="formkit_ninja_nodechildren",
                    when="AFTER",
                ),
            ),
        ),
        migrations.RunSQL(SEED_EXISTING_GROUPS, migrations.RunSQL.noop),
    ]
